SET FOREIGN_KEY_CHECKS=1;
SET storage_engine=InnoDB;
CREATE DATABASE IF NOT EXISTS PALESTRA;
USE PALESTRA;

DROP TABLE IF EXISTS PROGRAMMA;
DROP TABLE IF EXISTS CORSI;
DROP TABLE IF EXISTS ISTRUTTORE;


CREATE TABLE ISTRUTTORE(
CodFisc CHAR(20) NOT NULL,
Nome CHAR(15) NOT NULL,
Cognome CHAR(15) NOT NULL,
DataNascita DATE NOT NULL,
Email CHAR(50) NOT NULL,
Telefono CHAR(15) NULL,
PRIMARY KEY(CodFisc)
);

CREATE TABLE CORSI(
CodC CHAR(5) NOT NULL,
Nome CHAR(30) NOT NULL,
Tipo CHAR(30) NOT NULL,
Livello SMALLINT NOT NULL CHECK(Livello>0 AND Livello<5),
PRIMARY KEY(CodC)
);

CREATE TABLE PROGRAMMA(
CodFisc CHAR(20) NOT NULL,
Giorno CHAR(10) NOT NULL,
OraInizio TIME NOT NULL, 
Durata SMALLINT NOT NULL,
CodC CHAR(5) NOT NULL,
Sala CHAR(5) NOT NULL,
PRIMARY KEY(CodC, Giorno, OraInizio),
FOREIGN KEY(CodFisc) REFERENCES ISTRUTTORE(CodFisc)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
FOREIGN KEY(CodC) REFERENCES CORSI(CodC)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

